export const fieldMapping = {
    "SrNo": "SrNo",
    "Packet Id": "Stock ID",
    "Status": "Availability",
    "Show ID": "Show ID",
    "Shape": "Shape",
    "CRTWT": "CRTWT",
    "RAP RATE": "RAP RATE",
    "RAP DIS": "RAP DIS",
    "RATE": "RATE",
    "Amount": "Amount",
    "COL": "COL",
    "CLR": "CLR",
    "CUT": "CUT",
    "POL": "POL",
    "SYM": "SYM",
    "FLU": "Flur",
    "Measurement": "Measurement",
    "DIA MN": "DIA MN",
    "DIA MX": "DIA MX",
    "LN": "LN",
    "WD": "WD",
    "LW": "LW",
    "DPL": "DPL",
    "TBL": "TBL",
    "Girdle": "Girdle",
    "Lab": "Lab",
    "Shade": "Shade",
    "Natts": "Natts",
    "Milky": "Milky",
    "Inscription": "Inscription",
    "Certificate No": "Certificate No",
    "Comments": "Comments",
    "KTSVIEW": "KTSVIEW",
    "Certificate Date": "Certificate Date",
    "Transfer Date": "",
    "BPF Issue Date": "",
    "CA": "CA",
    "CH": "CH",
    "PA": "PA",
    "PD": "PD",
    "DEPT": "DEPT",
    "SIZE": "SIZE",
    "Type 2a": "Type 2a",
    "EC": "EC",
    "SAL BYR": "",
    "LOCATION": "LOCATION",
    "EFFM": "EFFM",
    "Category": "Category",
    "Rap Value": "Rap Value",
    "OPTA": "OPTA",
    "OPCR": "OPCR",
    "OPPV": "OPPV",
    "Culet": "Culet",
    "Revise Date": "",
    "LABTYPE": ""
}